name: Notify Hugo Site on Content Update

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Hugo Site Build
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.HUGO_REPO_PAT }}" \
            https://api.github.com/repos/Beyond-The-Bench/BeyondTheBench/dispatches \
            -d '{"event_type":"content-updated"}'
